### ISSUE TITLE
Sprites not showing/functioning

### ISSUE THREAD

**Issue by GL513** [leopard-js/leopard#102]
The first time I used Leopard, it worked completely fine. I could see all the sprites, the costumes worked fine, the only problem i had was the framerate, which appears to only be the computer.
Some sprites that have been converted aren't showing, aren't functioning at all, or both.
I have the same result in the website frame as I do in the CodeSandbox page.

[This](https://cdn.discordapp.com/attachments/836164219073331213/869975457355948152/unknown.png) is the expected result, but [this](https://cdn.discordapp.com/attachments/836164219073331213/t869975337159778364/unknown.png) is what I get.
I'm not sure what is causing this at all.

**Comment by towerofnix** [comment]
We aren't able to debug this without a link to the project (which I'm super late to ask for now, sorry :P). By the sounds of it, it might've been a rate limiting issue — CodeSandbox is tricky for really large projects because Leopard downloads each asset file (costume, sound) one by one instead of all in one big file, and CodeSandbox doesn't like getting a ton of requests from one client (your computer) all at once.

**Comment by GL513** [comment]
Ah okay, that makes sense. I'll try to replicate my issue later on to try again, thank you.
