### ISSUE TITLE
Ability to disable Renderer._resize()

### ISSUE THREAD

**Issue by mavthedev** [leopard-js/leopard#147]
Currently working on a project and i want my canvas element to stay as a square as big as possible but still leave room for the elements on the other side, but whenever i change the height the canvas element immediately goes back to being a rectangle

**Comment by towerofnix** [comment]
The `_resize` function doesn't have any specific behavior for making a rectangle, it just tries to respect the stage's `width` and `height` properties. Have you tried [initially updating](https://github.com/leopard-js/leopard/blob/3822bdbdf4083c29df6895006f67062371845847/src/Sprite.js#L632-L647) the stage's dimensions?

I.e, at the top-level `index.js`, updating your `const stage` line like this:

```js
const stage = new Stage({
  costumeNumber: 1, // or whatever

  width: 400,
  height: 400,
});
```

I haven't worked with the canvas/DOM parts of Leopard in a while, but you will probably have better luck maintaining a square instead of a rectangle this way!
