### ISSUE TITLE
Haven't published a new release in a while

### ISSUE THREAD

**Issue by PullJosh** [leopard-js/leopard#186]
@towerofnix and @adroitwhiz I realized we have made a ton of changes without publishing a release to npm. I'm not sure how that happened. Is there anything blocking us from making one right now so that users can get all the little improvements we've made?

**Comment by towerofnix** [comment]
We're assuming [1.5.1](https://github.com/leopard-js/leopard/releases/tag/1.5.1) is the latest release, on both [NPM](https://www.npmjs.com/package/leopard) and the Leopard website, right?

Here's [a handy search](https://github.com/pulls?q=org%3Aleopard-js+is%3Amerged+sort%3Aupdated-desc+updated%3A%3E%3D2023-03-13+) - here's everything merged since 1.5.1:

* Typescript [improvements for sb-edit](https://github.com/leopard-js/sb-edit/pull/94) and [first implementation for Leopard](https://github.com/leopard-js/leopard/pull/146)
* Housekeeping (dependency updates & miscellaneous) for both [Leopard](https://github.com/leopard-js/leopard/pull/185) and [sb-edit](https://github.com/leopard-js/sb-edit/pull/121)
* leopard-js/sb-edit#118
* leopard-js/sb-edit#124

Most of these have no behavior changes, so there should be no danger at all in publishing an NPM release (and to the site) including them. leopard-js/sb-edit#118 is a fix for serializing the rotation style saved on sprites, which is good for conversion compatibility.

---

Currently in-progress on sb-edit:

* leopard-js/sb-edit#122
  * Test project ready, pending on resolving name of "times" variable against custom arg names. (This isn't a lot of work, just been occupied elsewhere last few days.)
* leopard-js/sb-edit#123
  * Implementation done, pending on writing a test project. (There are a lot of blocks to test, so this is going to be tedious to put together, but not challenging...)

Not yet started, but on our sooner-and-later todo list for sb-edit:

* leopard-js/sb-edit#120
  * Not a compatibility issue, but will help lots of variables serialize nicer.
* Investigate https://github.com/leopard-js/sb-edit/issues/9#issuecomment-1869879710
* Eventually investigate leopard-js/sb-edit#112

We'll get to leopard-js/sb-edit#122 quite soon. Test project for leopard-js/sb-edit#123 will likely take a bit longer. The other todos don't have any times set in stone yet, but we do have a path forward for leopard-js/sb-edit#120; the others are probably a ways off.

---

Our main "job" (volunteer / long-term passion project, lol) is a wide berth of data, code, community and maintenance work on @hsmusic (https://hsmusic.wiki/), so Leopard generally comes second to that and/or other stuff that we're busy with IRL. We care about Leopard a lot, obviously!! Just got responsibilities elsewhere, as most anyone does. ^^

**Comment by PullJosh** [comment]
Thank you! This was a very helpful lay of the land. I didn't know you could search for all PRs across repos like that. I've published new releases of leopard and sb-edit that include all our changes. I'm hopeful that shipping typescript types for Leopard will be useful to people.

> Leopard generally comes second to [hsmusic] and/or other stuff that we're busy with IRL. We care about Leopard a lot, obviously!! Just got responsibilities elsewhere, as most anyone does. ^^

Of course! I have been surprised and very appreciative of how much you and @adroitwhiz have been willing to help, but I never expect anything. Please continue to prioritize everything you need to prioritize over Leopard, and only contribute if/when it's fun. 😄
