### ISSUE TITLE
Best way to handle loading project assets?

### ISSUE THREAD

**Issue by adroitwhiz** [leopard-js/leopard#38]
Currently, `Costume`s don't appear until their images are loaded, and sounds only play once they're loaded.

There are some APIs that would greatly benefit from `Costume`s' images being loaded at construction-time, and projects not being "*really* loaded" until some inteterminate point in the future is not ideal.

To fix this, there would need to be some sort of API for loading a project and all its assets, but I'm not sure what that would look like.

**Comment by PullJosh** [comment]
This has become a high-priority issue with the WebGL renderer, because it causes projects to lock up on the scratch-js website. (I think loading cross-domain assets from Scratch makes the error a bigger deal.)

If we can just add a loading sign of some kind (probably added with HTML rather than drawn on a canvas), that would be enough. I don't think it's necessary to allow loading extra assets while a project is running.

**Comment by adroitwhiz** [comment]
It's odd that projects are locking up--the costumes should currently just not render until they load. Which projects are doing this?

**Comment by PullJosh** [comment]
Basically all of them. Try pasting in a new project URL on the [homepage](https://scratch-js.now.sh/).

**Comment by adroitwhiz** [comment]
That's weird. I got it to happen exactly once in Chrome (it gave the error `Failed to execute 'texImage2D' on 'WebGL2RenderingContext': The image element contains cross-origin data, and may not be loaded`), but every time after that, it just didn't render.

Even when I created a different project, disabled the cache, and throttled the connection, I couldn't reproduce this any further.

**Comment by PullJosh** [comment]
Super strange. I can recreate it pretty consistently without any real effort. :P

For the record, here's what I'm seeing with project `357224762`:

![image](https://user-images.githubusercontent.com/5458180/71792863-60cada80-3008-11ea-859a-a4a92ba162ae.png)
The actual stage is all white, which I assume is because we were never able to successfully render a frame.

**Comment by PullJosh** [comment]
[Looks like](https://github.com/ml5js/ml5-library/issues/217#issuecomment-424085565) it might be as easy as reordering these lines: https://github.com/PullJosh/scratch-js/blob/ac9a4ca4ad73b4f8c1bedf7924e2ce065559528f/scratch-js/Costume.mjs#L7-L8

Will try when I get the opportunity.

**Comment by PullJosh** [comment]
Okay, I think [that](https://github.com/PullJosh/scratch-js/commit/67b905f256ba5c853ee66dc0646d45d57f53eadc) fixed the issue. 👍

**Comment by adroitwhiz** [comment]
There still needs to be a better API for loading projects, IMO. Currently, you make a project with `new Project()`, which is synchronous.

I was leaning towards replacing the `Project` constructor with `Project.from()` or something like that, which returns a `Promise<Project>`.

The [PIXI Loader API](https://pixijs.download/dev/docs/PIXI.Loader.html) might be helpful to look at as well.

**Comment by PullJosh** [comment]
It would be nice to render a loading bar, which would require the `Project` to exist and be mounted to a DOM element before all the assets have loaded. I think that pretty much rules out returning a `Promise<Project>`.

Instead, what if `progress.progress()` gave a number between `0` and `1` and while the project was loading, the `Renderer` added a simple loading bar DOM element (customizable with CSS)?

We could also have `project.on('load', myCallback)` if that's something that would be useful to users...

**Comment by PullJosh** [comment]
Closing in favor of #133
