### ISSUE TITLE
Click on Stage triggered even when it should not

### ISSUE THREAD

**Issue by sfederici** [leopard-js/leopard#77]
In project https://scratch.mit.edu/projects/305593150/ if you can click on the stage to activate the zoom feature. It seems that the click on the Stage is triggered even when you click on a sprite. For example, if I click the "reset" sprite, that is supposed to bring the view back to the starting point, what I get instead is a zoom, the click on the sprite is not taken into account (or at least the click on the Stage is triggered anyway, even if it should not)

**Comment by sfederici** [comment]
I tried converting again the project https://scratch.mit.edu/projects/305593150/, but the "converting" rotating shape goes on forever (both in Chrome and Firefox)

**Comment by towerofnix** [comment]
@PullJosh Not sure what the system is like ATM to ensure leopardjs.com's code sandbox generation uses up-to-date `leopard` and `sb-edit` dependencies? Either way not ideal that this would fail silently (I get a 504 gateway timeout error that the Leopard site doesn't detect/show an error for), network response below:

```
GET https://leopardjs.com/api/305593150/codesandbox
504 Gateway Timeout

An error occurred with your deployment

FUNCTION_INVOCATION_TIMEOUT
```

(nb: other projects still load)

Haven't yet tested this project locally to see if it does error locally with current Leopard code and/or just before recent changes. Something must've changed either in the codebase or on the site to prevent the project from loading since it did load back when this issue was opened in 2020.
