### ISSUE TITLE
Where to start fixing Leopard

### ISSUE THREAD

**Issue by sfederici** [leopard-js/leopard#85]
As to projects that do not translate, e.g. the ones listed at https://github.com/PullJosh/leopard/issues/74, are there any cue as to where to start looking at?

**Comment by adroitwhiz** [comment]
The project translation itself is done in [sb-edit](https://github.com/PullJosh/sb-edit). I'd start by looking at the translated code and comparing it with the Scratch code, starting with the simplest projects first, and seeing where behavior diverges between the Scratch and Leopard code.

Also, even with the large number of projects which don't translate, I'd create a new issue for each project (as long as @PullJosh is okay with that) so that each issue can be closed independently when its project is fixed.

**Comment by sfederici** [comment]
> starting with the simplest projects first

I already successfully translated a lot of simple and less simple projects. I have problems just with the very complex projects I listed.

> Also, even with the large number of projects which don't translate, I'd create a new issue for each project 

Ok

> I'd start by looking at the translated code and comparing it with the Scratch code

**Comment by towerofnix** [comment]
I'm going to close this in favor of addressing open issues, or opening new ones for projects which currently don't translate. Overall support is pretty good right now, so the big focus is on compatibility (behavior differences between Scratch 3.0 and Leopard) and missing blocks (see ["support" label](https://github.com/leopard-js/leopard/issues?q=is%3Aissue+is%3Aopen+label%3Asupport)). Sounds like the question here was basically answered but feel free to comment or open a new issue if you are wondering anything else :)
