### ISSUE TITLE
How to scale stage image to fit window size

### ISSUE THREAD

**Issue by aljonka** [leopard-js/leopard#97]
Hi,

great project :-) Thank you for it. One question, the stage size is set to 480/360. Is there possibility to resize the stage image to fit window size?

Thanks a lot

**Comment by Mikeowsky-2104** [comment]
Yes 
it is

**Comment by aljonka** [comment]
Sounds great. I can resize stage (for Firefox), however the picture of stage remains unchanged.

`class U extends O {
    constructor(t, ...e) {
        super(t, ...e), Object.defineProperties(this, {
            width: {
                value: t.width || window.innerWidth, //480
                enumerable: !0
            },
            height: {
                value: t.height || window.innerHeight, //360
                enumerable: !0
            }
        }), this.name = "Stage", this.__counter = 0
    }
}`

And in the Stage.js

export default class Stage extends StageBase {
  constructor(...args) {
    super(...args);

    this.costumes = [
      new Costume("Bunenbild1", "./Stage/costumes/Bunenbild1.png", {
        x: window.innerWidth,   //480,
        y: window.innerHeight,  //360
      })
    ];

Any hint what is wrong?

Thank you

**Comment by HanClinto** [comment]
It's a bit simpler than this, but it looks to be undocumented, so it was a bit tricky to track down.

In your `index.js` of your project, when you create your Stage, you can set the Width and Height of the object that's passed in:
```
const stage = new Stage({ costumeNumber: 1, width: 1000, height: 600 });
```

You can also make this go off of the size of the window at the time that the page was loaded:

```
const stage = new Stage({ costumeNumber: 1, width: window.innerWidth, height: window.innerHeight });
```

Note that this doesn't look quite right, because it tries to set it to the FULL size of the window (which doesn't account for the `body`'s border, nor the Green Flag button at the top).  So if you want this to have a nicer margin around the edge, you can just subtract a little and it'll look nice:

```
const stage = new Stage({ costumeNumber: 1, width: window.innerWidth-16 /* Body border */ , height: window.innerHeight-36 /* Body border + Green Flag button */ });
```
![image](https://user-images.githubusercontent.com/796749/179329330-b9f86298-6bfb-4429-ae74-61e37a17cbe8.png)

Note that Leopard does not support dynamic resizing of the stage (yet?), so if you want to resize the window, you'll need to reload the page.

**Comment by towerofnix** [comment]
I'm going to close this as @HanClinto's answer is quite comprehensive for the current state! We don't support dynamic resizing (yet), so matching the window's initial size may be the best you can do right now.

It's also technically possible to resize the `<canvas>` element itself to fill up the screen using CSS ([example here](https://github.com/leopard-js/sb-edit/issues/85#issuecomment-1433900774), just edit `index.html`). Just keep in mind that it *might* cause blurring, and definitely isn't compatible with monitors (like shown variables and lists), which expect the canvas to be the same size as the stage.
